#! /usr/bin/python3

import sys
from tig_init import tig_init
from tig_add import tig_add
from tig_commit import tig_commit
from tig_status import tig_status
from tig_diff import tig_diff
from tig_catfile import tig_catfile
from tig_reset import tig_reset

# 获取命令行参数
args = sys.argv[1:]

# 检查命令行参数并执行相应的操作
if len(args) == 0:
    print("Usage: tig <command>")
    print("Available commands: init, add, commit, status, diff, reset, cat-file")
elif args[0] == "init":
    tig_init()
elif args[0] == "add":
    args = sys.argv[2:]
    tig_add(args)
elif args[0] == "commit":
    tig_commit()
elif args[0] == "status":
    tig_status()
elif args[0] == "diff":
    tig_diff()
elif args[0] == "reset":
    tig_reset()
elif args[0] == "cat-file":
    args = sys.argv[2:]
    if len(args) != 2:
        print("Invalid number of arguments. Usage: tig cat-file <option> <md5>")
        sys.exit(1)
    option = args[0]
    md5 = args[1]

    tig_catfile(option, md5)
else:
    print("Unknown command:", args[0])